FROM node:18-alpine

WORKDIR /.

COPY package*.json package.json
COPY package-lock.json package-lock.json
COPY prisma ./prisma/ 

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD [ "npm", "run", "start"]